services:
  frontend:
    image: ghcr.io/${REPO_NAME}:latest
    container_name: qazdocs-frontend
    ports:
      - "3010:80"
    restart: unless-stopped
    networks:
      - qazcode_network

networks:
  qazcode_network:
    external: true
